version: "3.9"
services:
  api:
    image: akuamakana/splat-api:latest
    container_name: api
    # build: ./server/.
    links:
      - redis
      - db
    depends_on:
      - db
    environment:
      - PORT=3001
      - SESSION_SECRET=qmNi6At37515NiwbhZE34MW9POkSpY0W
      - COOKIE_NAME=zid
      - REDIS_HOST=redis
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=9EberIVKtqQaDWzvTlMpX49U0qT3bw5E
      - FRONTEND_URL=http://localhost
    ports:
      - "3001:3001"
    networks:
      - splat-api
    restart: always

  client:
    image: akuamakana/splat-client:latest
    container_name: client
    # build:
    #   context: ./web/.
    #   args:
    #     - API_URL=http://api.localhost
    links:
      - redis
      - db
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_URL=http://api.localhost
    networks:
      - splat-api

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    networks:
      - splat-api

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=splat
      - POSTGRES_PASSWORD=9EberIVKtqQaDWzvTlMpX49U0qT3bw5E
    ports:
      - 5432:5432
    networks:
      - splat-api
    volumes:
      - ./data:/var/lib/postgresql/

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    depends_on:
        - api
        - client
    build:
        context: ./nginx
        dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    ports:
        - 80:80
        - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
        - splat-api

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - api

networks:
  splat-api:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/akuamakana/Source/Repos/splat/server/
      o: bind
