version: "3.9"
services:
  api:
    image: akuamakana/splat-api:latest
    container_name: api
    build: ./server/.
    links:
      - redis
      - db
    depends_on:
      - db
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    networks:
      - splat-api
    restart: always

  client:
    image: akuamakana/splat-client:latest
    container_name: client
    build:
      context: ./web/.
      args:
        api_url: http://localhost:3001
    links:
      - redis
      - db
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - splat-api

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    networks:
      - splat-api

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    networks:
      - splat-api
    volumes:
      - ./data:/var/lib/postgresql/

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    depends_on:
        - api
        - client
    build:
        context: ./nginx
        dockerfile: Dockerfile
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
    ports:
        - 8080:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
        - splat-api

networks:
  splat-api:
    driver: bridge