version: "3.3"
services:
  api:
    build: .
    ports:
      - "3001:3001"
    links:
      - redis
    #   - db
    # depends_on:
    #   - db
    environment:
      PORT: 3001
      SESSION_SECRET: corgicarbonara
      COOKIE_NAME: zid
      REDIS_HOST: redis
      TYPEORM_HOST: splatdb-instance-1.cbbdvexrck2z.us-west-2.rds.amazonaws.com
      TYPEORM_USERNAME: splatAdmin
      TYPEORM_PASSWORD: rqUIwRtJUXM6KraDMMtc
      # TYPEORM_PASSWORD: UzQ0u1l36z96KGeyWOoK

  web:
    build: ../web/.
    ports:
      - "3000:3000"
    links:
      - api

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: splat
  #     POSTGRES_PASSWORD: Hawaii3274!
  #     PGDATA: /data/postgres
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - "5432"